#####################
# CraftManager config
#####################
#

#Location.toString() of the main lobby to be used with /lobby
lobby:
  world: world
  x: 567.5
  y: 74
  z: 12.5
  yaw: 0
  pitch: 0
